-- =====================================================================
-- Full guest list for Isaac & Corine wedding
-- Database: itoprogress2_isaac_corine
-- Generated: 2026-02-23
--
-- Total: 274 real guests + 5 test entries = 279
--
-- USAGE: Run this in phpMyAdmin (SQL tab). It deletes all existing
--        rows first, then re-inserts everyone fresh.
-- =====================================================================

DELETE FROM guests WHERE tenant_id = 'isaac-and-corine';

INSERT INTO guests (tenant_id, name, name_lower, plus_one, plus_one_name, rsvp_status) VALUES
('isaac-and-corine', 'Pierre Zoghzoghi', 'pierre zoghzoghi', 1, NULL, 'pending'),
('isaac-and-corine', 'Tala Mardelli', 'tala mardelli', 0, NULL, 'pending'),
('isaac-and-corine', 'Toufic Tager', 'toufic tager', 0, NULL, 'pending'),
('isaac-and-corine', 'Karina Abella', 'karina abella', 0, NULL, 'pending'),
('isaac-and-corine', 'Oliver Dabar', 'oliver dabar', 1, NULL, 'pending'),
('isaac-and-corine', 'Jen Nahas', 'jen nahas', 1, NULL, 'pending'),
('isaac-and-corine', 'Paul-Antoine Khoury', 'paul-antoine khoury', 0, NULL, 'pending'),
('isaac-and-corine', 'Yara Nahas', 'yara nahas', 0, NULL, 'pending'),
('isaac-and-corine', 'Joe Sabbagh', 'joe sabbagh', 1, NULL, 'pending'),
('isaac-and-corine', 'Yasmina Saradar', 'yasmina saradar', 0, NULL, 'pending'),
('isaac-and-corine', 'Bruno Bakhach', 'bruno bakhach', 0, NULL, 'pending'),
('isaac-and-corine', 'Andra Khouri', 'andra khouri', 0, NULL, 'pending'),
('isaac-and-corine', 'Malek Murr', 'malek murr', 1, NULL, 'pending'),
('isaac-and-corine', 'Marijo Mathieu', 'marijo mathieu', 0, NULL, 'pending'),
('isaac-and-corine', 'Marc Akhras', 'marc akhras', 0, NULL, 'pending'),
('isaac-and-corine', 'Sandrine Chedid', 'sandrine chedid', 0, NULL, 'pending'),
('isaac-and-corine', 'Philippe Zoghzoghi', 'philippe zoghzoghi', 0, NULL, 'pending'),
('isaac-and-corine', 'Daniele Anid', 'daniele anid', 1, NULL, 'pending'),
('isaac-and-corine', 'Ralph Gharios', 'ralph gharios', 0, NULL, 'pending'),
('isaac-and-corine', 'Emma Hawa', 'emma hawa', 0, NULL, 'pending'),
('isaac-and-corine', 'Nicolas Hassoun', 'nicolas hassoun', 0, NULL, 'pending'),
('isaac-and-corine', 'Georges Keyrouz', 'georges keyrouz', 1, NULL, 'pending'),
('isaac-and-corine', 'Alya Gaspard', 'alya gaspard', 0, NULL, 'pending'),
('isaac-and-corine', 'Omar Farhat', 'omar farhat', 1, NULL, 'pending'),
('isaac-and-corine', 'Jane Zakhem', 'jane zakhem', 1, NULL, 'pending'),
('isaac-and-corine', 'Ralph Khayat', 'ralph khayat', 0, NULL, 'pending'),
('isaac-and-corine', 'Della Mecattaf', 'della mecattaf', 1, NULL, 'pending'),
('isaac-and-corine', 'Michel Bejjani', 'michel bejjani', 0, NULL, 'pending'),
('isaac-and-corine', 'Demy Abi Khalil', 'demy abi khalil', 0, NULL, 'pending'),
('isaac-and-corine', 'Chris Salamoun', 'chris salamoun', 1, NULL, 'pending'),
('isaac-and-corine', 'Tania Bteich', 'tania bteich', 0, NULL, 'pending'),
('isaac-and-corine', 'Ziad Chehab', 'ziad chehab', 0, NULL, 'pending'),
('isaac-and-corine', 'Mia Eid', 'mia eid', 1, NULL, 'pending'),
('isaac-and-corine', 'Joseph Merhej', 'joseph merhej', 1, NULL, 'pending'),
('isaac-and-corine', 'Diala Rizk', 'diala rizk', 1, NULL, 'pending'),
('isaac-and-corine', 'Roger Chaccour', 'roger chaccour', 0, NULL, 'pending'),
('isaac-and-corine', 'Nadine Araygi', 'nadine araygi', 1, NULL, 'pending'),
('isaac-and-corine', 'Iyad Achkar', 'iyad achkar', 1, NULL, 'pending'),
('isaac-and-corine', 'Celine Bteich', 'celine bteich', 1, NULL, 'pending'),
('isaac-and-corine', 'Pierre-Christophe Antoun', 'pierre-christophe antoun', 0, NULL, 'pending'),
('isaac-and-corine', 'Melissa Haddad', 'melissa haddad', 1, NULL, 'pending'),
('isaac-and-corine', 'Michael Soumrani', 'michael soumrani', 1, NULL, 'pending'),
('isaac-and-corine', 'Lana Zir', 'lana zir', 0, NULL, 'pending'),
('isaac-and-corine', 'Anthony Salamoun', 'anthony salamoun', 0, NULL, 'pending'),
('isaac-and-corine', 'Leya Hage', 'leya hage', 1, NULL, 'pending'),
('isaac-and-corine', 'Marc Nasr', 'marc nasr', 1, NULL, 'pending'),
('isaac-and-corine', 'Lea Acra', 'lea acra', 1, NULL, 'pending'),
('isaac-and-corine', 'Jean Paul Chidiac', 'jean paul chidiac', 1, NULL, 'pending'),
('isaac-and-corine', 'Raya Khayat', 'raya khayat', 1, NULL, 'pending'),
('isaac-and-corine', 'Carl Daou', 'carl daou', 1, NULL, 'pending'),
('isaac-and-corine', 'Nayla Nasr', 'nayla nasr', 0, NULL, 'pending'),
('isaac-and-corine', 'Tarek Abboud', 'tarek abboud', 0, NULL, 'pending'),
('isaac-and-corine', 'Julie Abou Moussa', 'julie abou moussa', 0, NULL, 'pending'),
('isaac-and-corine', 'Edmond Rizk', 'edmond rizk', 1, NULL, 'pending'),
('isaac-and-corine', 'Sarah Abou Moussa', 'sarah abou moussa', 0, NULL, 'pending'),
('isaac-and-corine', 'Anthony Attieh', 'anthony attieh', 0, NULL, 'pending'),
('isaac-and-corine', 'Edwina Daher', 'edwina daher', 0, NULL, 'pending'),
('isaac-and-corine', 'Claude Zoghzoghi', 'claude zoghzoghi', 1, NULL, 'pending'),
('isaac-and-corine', 'Rita El Am', 'rita el am', 1, NULL, 'pending'),
('isaac-and-corine', 'Anthony Michael', 'anthony michael', 0, NULL, 'pending'),
('isaac-and-corine', 'Nicole Araygi', 'nicole araygi', 1, NULL, 'pending'),
('isaac-and-corine', 'Cyril Irani', 'cyril irani', 0, NULL, 'pending'),
('isaac-and-corine', 'Lea Tager', 'lea tager', 0, NULL, 'pending'),
('isaac-and-corine', 'Gio Fikani', 'gio fikani', 0, NULL, 'pending'),
('isaac-and-corine', 'Fouad Farhat', 'fouad farhat', 1, NULL, 'pending'),
('isaac-and-corine', 'Sasha Khayat', 'sasha khayat', 0, NULL, 'pending'),
('isaac-and-corine', 'Eddy Nasr', 'eddy nasr', 1, NULL, 'pending'),
('isaac-and-corine', 'Karim Zeino', 'karim zeino', 0, NULL, 'pending'),
('isaac-and-corine', 'Gabriel Edde', 'gabriel edde', 0, NULL, 'pending'),
('isaac-and-corine', 'Aude Corruzzi', 'aude corruzzi', 1, NULL, 'pending'),
('isaac-and-corine', 'Romain Ouaiss', 'romain ouaiss', 0, NULL, 'pending'),
('isaac-and-corine', 'Charlotte Robson', 'charlotte robson', 0, NULL, 'pending'),
('isaac-and-corine', 'Camil Abou Farhat', 'camil abou farhat', 0, NULL, 'pending'),
('isaac-and-corine', 'Jade Flaviano', 'jade flaviano', 1, NULL, 'pending'),
('isaac-and-corine', 'Elio Abou Farhat', 'elio abou farhat', 0, NULL, 'pending'),
('isaac-and-corine', 'Hugo Mendes', 'hugo mendes', 0, NULL, 'pending'),
('isaac-and-corine', 'Marc Zoghzoghi', 'marc zoghzoghi', 0, NULL, 'pending'),
('isaac-and-corine', 'Jean Beaufigeau', 'jean beaufigeau', 1, NULL, 'pending'),
('isaac-and-corine', 'Henri Saab', 'henri saab', 1, NULL, 'pending'),
('isaac-and-corine', 'Emanuel Malz', 'emanuel malz', 0, NULL, 'pending'),
('isaac-and-corine', 'Paul-Helie Magdelenat', 'paul-helie magdelenat', 0, NULL, 'pending'),
('isaac-and-corine', 'Nour Rizk', 'nour rizk', 0, NULL, 'pending'),
('isaac-and-corine', 'Issam Arris', 'issam arris', 0, NULL, 'pending'),
('isaac-and-corine', 'Maria Abou Farhat', 'maria abou farhat', 0, NULL, 'pending'),
('isaac-and-corine', 'Carl Abou Jaoude', 'carl abou jaoude', 1, NULL, 'pending'),
('isaac-and-corine', 'Joanna Ziade', 'joanna ziade', 1, NULL, 'pending'),
('isaac-and-corine', 'Cynthia Braidy', 'cynthia braidy', 0, NULL, 'pending'),
('isaac-and-corine', 'Gabriel Bazergi', 'gabriel bazergi', 0, NULL, 'pending'),
('isaac-and-corine', 'Luana Fakhoury', 'luana fakhoury', 0, NULL, 'pending'),
('isaac-and-corine', 'Malek Arif', 'malek arif', 0, NULL, 'pending'),
('isaac-and-corine', 'Tatiana Abou Mrad', 'tatiana abou mrad', 0, NULL, 'pending'),
('isaac-and-corine', 'Pierre Mecattaf', 'pierre mecattaf', 0, NULL, 'pending'),
('isaac-and-corine', 'Alex Abou Jaoude', 'alex abou jaoude', 0, NULL, 'pending'),
('isaac-and-corine', 'Yara Moujaes', 'yara moujaes', 0, NULL, 'pending'),
('isaac-and-corine', 'Raphael Gilson', 'raphael gilson', 0, NULL, 'pending'),
('isaac-and-corine', 'Joanna Debs', 'joanna debs', 0, NULL, 'pending'),
('isaac-and-corine', 'Boutros Khoury', 'boutros khoury', 0, NULL, 'pending'),
('isaac-and-corine', 'Lama Soueidan', 'lama soueidan', 0, NULL, 'pending'),
('isaac-and-corine', 'Khalil Sarraf', 'khalil sarraf', 0, NULL, 'pending'),
('isaac-and-corine', 'Nicole Khoury', 'nicole khoury', 1, NULL, 'pending'),
('isaac-and-corine', 'Rami Karaki', 'rami karaki', 0, NULL, 'pending'),
('isaac-and-corine', 'Lynn Lahoud', 'lynn lahoud', 0, NULL, 'pending'),
('isaac-and-corine', 'Eli Hindi', 'eli hindi', 1, NULL, 'pending'),
('isaac-and-corine', 'Mia Boustany', 'mia boustany', 1, NULL, 'pending'),
('isaac-and-corine', 'Cesar Bteish', 'cesar bteish', 0, NULL, 'pending'),
('isaac-and-corine', 'Ariane Gemayel', 'ariane gemayel', 1, NULL, 'pending'),
('isaac-and-corine', 'Claudia Nader', 'claudia nader', 0, NULL, 'pending'),
('isaac-and-corine', 'Karim et Julie Saddi', 'karim et julie saddi', 1, NULL, 'pending'),
('isaac-and-corine', 'Yara Gemayel', 'yara gemayel', 0, NULL, 'pending'),
('isaac-and-corine', 'Thierry et Raya Edde', 'thierry et raya edde', 1, NULL, 'pending'),
('isaac-and-corine', 'Shirine Yacoub', 'shirine yacoub', 0, NULL, 'pending'),
('isaac-and-corine', 'Alice Keyrouz', 'alice keyrouz', 0, NULL, 'pending'),
('isaac-and-corine', 'Yasmine Kabbara', 'yasmine kabbara', 0, NULL, 'pending'),
('isaac-and-corine', 'Michelle Sadaka', 'michelle sadaka', 0, NULL, 'pending'),
('isaac-and-corine', 'Stephanie Sadaka', 'stephanie sadaka', 1, NULL, 'pending'),
('isaac-and-corine', 'Tarek Ghosn', 'tarek ghosn', 1, NULL, 'pending'),
('isaac-and-corine', 'Synda Machalani', 'synda machalani', 1, NULL, 'pending'),
('isaac-and-corine', 'Ralph Dib', 'ralph dib', 0, NULL, 'pending'),
('isaac-and-corine', 'Elias Ghosn', 'elias ghosn', 0, NULL, 'pending'),
('isaac-and-corine', 'Elissa Ghosn', 'elissa ghosn', 0, NULL, 'pending'),
('isaac-and-corine', 'Georges Ghosn', 'georges ghosn', 0, NULL, 'pending'),
('isaac-and-corine', 'Jack Ghosn', 'jack ghosn', 1, NULL, 'pending'),
('isaac-and-corine', 'Michael Ghosn', 'michael ghosn', 1, NULL, 'pending'),
('isaac-and-corine', 'Christophe karam', 'christophe karam', 1, NULL, 'pending'),
('isaac-and-corine', 'Karim Dahan', 'karim dahan', 1, NULL, 'pending'),
('isaac-and-corine', 'Elie hamouche', 'elie hamouche', 0, NULL, 'pending'),
('isaac-and-corine', 'Anthony jabbour', 'anthony jabbour', 1, NULL, 'pending'),
('isaac-and-corine', 'Georges Rafi', 'georges rafi', 0, NULL, 'pending'),
('isaac-and-corine', 'Carl assaf', 'carl assaf', 0, NULL, 'pending'),
('isaac-and-corine', 'Mark Karam', 'mark karam', 0, NULL, 'pending'),
('isaac-and-corine', 'George Kamar', 'george kamar', 1, NULL, 'pending'),
('isaac-and-corine', 'Antoine Hadad', 'antoine hadad', 0, NULL, 'pending'),
('isaac-and-corine', 'Jad Makhlouf', 'jad makhlouf', 1, NULL, 'pending'),
('isaac-and-corine', 'Victor Habis', 'victor habis', 1, NULL, 'pending'),
('isaac-and-corine', 'Fayez Nohra', 'fayez nohra', 0, NULL, 'pending'),
('isaac-and-corine', 'Serge Sawma', 'serge sawma', 1, NULL, 'pending'),
('isaac-and-corine', 'Nicolas Mendez', 'nicolas mendez', 0, NULL, 'pending'),
('isaac-and-corine', 'Walid Rahme', 'walid rahme', 1, NULL, 'pending'),
('isaac-and-corine', 'Otto Hall', 'otto hall', 0, NULL, 'pending'),
('isaac-and-corine', 'Marc Moukarzel', 'marc moukarzel', 0, NULL, 'pending'),
('isaac-and-corine', 'Francesca Messa', 'francesca messa', 0, NULL, 'pending'),
('isaac-and-corine', 'Hady Rahme', 'hady rahme', 0, NULL, 'pending'),
('isaac-and-corine', 'Bharat Kaushish', 'bharat kaushish', 0, NULL, 'pending'),
('isaac-and-corine', 'Rawad Abou Jaoude', 'rawad abou jaoude', 0, NULL, 'pending'),
('isaac-and-corine', 'Sanya Kaushish', 'sanya kaushish', 0, NULL, 'pending'),
('isaac-and-corine', 'Remy Otayek', 'remy otayek', 0, NULL, 'pending'),
('isaac-and-corine', 'Daniel Dicienzo', 'daniel dicienzo', 1, NULL, 'pending'),
('isaac-and-corine', 'Patrick Malek', 'patrick malek', 0, NULL, 'pending'),
('isaac-and-corine', 'Warner Jenkins', 'warner jenkins', 0, NULL, 'pending'),
('isaac-and-corine', 'Ramzi Chamcham', 'ramzi chamcham', 0, NULL, 'pending'),
('isaac-and-corine', 'Madeleine Jenkins', 'madeleine jenkins', 0, NULL, 'pending'),
('isaac-and-corine', 'Luigi Irani', 'luigi irani', 0, NULL, 'pending'),
('isaac-and-corine', 'Chris Twyman', 'chris twyman', 0, NULL, 'pending'),
('isaac-and-corine', 'Christopher Tamari', 'christopher tamari', 1, NULL, 'pending'),
('isaac-and-corine', 'Zina Aczam', 'zina aczam', 0, NULL, 'pending'),
('isaac-and-corine', 'Joseph Bejjani', 'joseph bejjani', 1, NULL, 'pending'),
('isaac-and-corine', 'Sirine Rayess', 'sirine rayess', 0, NULL, 'pending'),
('isaac-and-corine', 'Faisal Barakat', 'faisal barakat', 0, NULL, 'pending'),
('isaac-and-corine', 'Elie Kareh', 'elie kareh', 0, NULL, 'pending'),
('isaac-and-corine', 'Rafael Otegui', 'rafael otegui', 1, NULL, 'pending'),
('isaac-and-corine', 'Philippe khoury', 'philippe khoury', 0, NULL, 'pending'),
('isaac-and-corine', 'Javier Pina', 'javier pina', 1, NULL, 'pending'),
('isaac-and-corine', 'Michel dibo', 'michel dibo', 0, NULL, 'pending'),
('isaac-and-corine', 'Michel Jurdak', 'michel jurdak', 0, NULL, 'pending'),
('isaac-and-corine', 'Mark Feghali', 'mark feghali', 1, NULL, 'pending'),
('isaac-and-corine', 'Joseph Kassab', 'joseph kassab', 0, NULL, 'pending'),
('isaac-and-corine', 'Brandon Somerhalder', 'brandon somerhalder', 1, NULL, 'pending'),
('isaac-and-corine', 'Pierre Chekrallah', 'pierre chekrallah', 0, NULL, 'pending'),
('isaac-and-corine', 'Anis Jebran', 'anis jebran', 0, NULL, 'pending'),
('isaac-and-corine', 'Paul Tabet', 'paul tabet', 0, NULL, 'pending'),
('isaac-and-corine', 'George Jebran', 'george jebran', 0, NULL, 'pending'),
('isaac-and-corine', 'Roy Boulos', 'roy boulos', 1, NULL, 'pending'),
('isaac-and-corine', 'Tanya Jebran', 'tanya jebran', 0, NULL, 'pending'),
('isaac-and-corine', 'Joey Nseir', 'joey nseir', 0, NULL, 'pending'),
('isaac-and-corine', 'Nasri Chedid', 'nasri chedid', 0, NULL, 'pending'),
('isaac-and-corine', 'Amanda Corm', 'amanda corm', 0, NULL, 'pending'),
('isaac-and-corine', 'Thea Corm', 'thea corm', 0, NULL, 'pending'),
('isaac-and-corine', 'Edouard Haber', 'edouard haber', 1, NULL, 'pending'),
('isaac-and-corine', 'Gaelle Corm', 'gaelle corm', 0, NULL, 'pending'),
('isaac-and-corine', 'Carl Abi Rached', 'carl abi rached', 0, NULL, 'pending'),
('isaac-and-corine', 'Sandra Sfeir', 'sandra sfeir', 0, NULL, 'pending'),
('isaac-and-corine', 'Fleurene Daraze', 'fleurene daraze', 1, NULL, 'pending'),
('isaac-and-corine', 'Jean-Pierre Sfeir', 'jean-pierre sfeir', 1, NULL, 'pending'),
('isaac-and-corine', 'Yasmina Sader', 'yasmina sader', 0, NULL, 'pending'),
('isaac-and-corine', 'Raya Sfeir', 'raya sfeir', 0, NULL, 'pending'),
('isaac-and-corine', 'Karim Abou Dib', 'karim abou dib', 1, NULL, 'pending'),
('isaac-and-corine', 'Georges Saghbini', 'georges saghbini', 1, NULL, 'pending'),
('isaac-and-corine', 'Tara Kanj', 'tara kanj', 0, NULL, 'pending'),
('isaac-and-corine', 'Marianne Saghbini', 'marianne saghbini', 1, NULL, 'pending'),
('isaac-and-corine', 'Cyril Keyrouz', 'cyril keyrouz', 0, NULL, 'pending'),
('isaac-and-corine', 'Michelle Abi Saad', 'michelle abi saad', 0, NULL, 'pending'),
('isaac-and-corine', 'Mario Noune', 'mario noune', 0, NULL, 'pending'),
('isaac-and-corine', 'Elie Abi Saad', 'elie abi saad', 0, NULL, 'pending'),
('isaac-and-corine', 'Victor Fayad', 'victor fayad', 0, NULL, 'pending'),
('isaac-and-corine', 'Joseph Doueihy', 'joseph doueihy', 0, NULL, 'pending'),
('isaac-and-corine', 'Elie Chalhoub', 'elie chalhoub', 0, NULL, 'pending'),
('isaac-and-corine', 'Jad Khalaf', 'jad khalaf', 1, NULL, 'pending'),
('isaac-and-corine', 'Ryan Kanj', 'ryan kanj', 0, NULL, 'pending'),
('isaac-and-corine', 'Roland Gemayel', 'roland gemayel', 0, NULL, 'pending'),
('isaac-and-corine', 'Jad Koundakjian', 'jad koundakjian', 0, NULL, 'pending'),
('isaac-and-corine', 'Lorenzo Boustany', 'lorenzo boustany', 0, NULL, 'pending'),
('isaac-and-corine', 'Karl Abou Zeid', 'karl abou zeid', 0, NULL, 'pending'),
('isaac-and-corine', 'Rony et Wadad Araygi', 'rony et wadad araygi', 0, NULL, 'pending'),
('isaac-and-corine', 'Jean et Carla Zoghzoghi', 'jean et carla zoghzoghi', 0, NULL, 'pending'),
('isaac-and-corine', 'Tony et Randa Eid', 'tony et randa eid', 0, NULL, 'pending'),
('isaac-and-corine', 'Samy et Emy Rizk', 'samy et emy rizk', 0, NULL, 'pending'),
('isaac-and-corine', 'Assad et Rana Maalouf', 'assad et rana maalouf', 0, NULL, 'pending'),
('isaac-and-corine', 'Michel et Marielle Mouawad', 'michel et marielle mouawad', 0, NULL, 'pending'),
('isaac-and-corine', 'Georges et Mirla Tabet', 'georges et mirla tabet', 0, NULL, 'pending'),
('isaac-and-corine', 'Gabriel et Paula Maalouly', 'gabriel et paula maalouly', 0, NULL, 'pending'),
('isaac-and-corine', 'Nabil et Pascale Asmar', 'nabil et pascale asmar', 0, NULL, 'pending'),
('isaac-and-corine', 'Philippe et Joselyne Maalouf', 'philippe et joselyne maalouf', 0, NULL, 'pending'),
('isaac-and-corine', 'Chaaya et Rita Atallah', 'chaaya et rita atallah', 0, NULL, 'pending'),
('isaac-and-corine', 'Fady et Mireille Rouhana', 'fady et mireille rouhana', 0, NULL, 'pending'),
('isaac-and-corine', 'Maurice et Shermine Iskandar', 'maurice et shermine iskandar', 0, NULL, 'pending'),
('isaac-and-corine', 'Alfred et June Kettaneh', 'alfred et june kettaneh', 0, NULL, 'pending'),
('isaac-and-corine', 'Marc et Gabrielle Assouad', 'marc et gabrielle assouad', 0, NULL, 'pending'),
('isaac-and-corine', 'Walid et Sandra Abou Farhat', 'walid et sandra abou farhat', 0, NULL, 'pending'),
('isaac-and-corine', 'Fares et Berthe Abboud', 'fares et berthe abboud', 0, NULL, 'pending'),
('isaac-and-corine', 'Nadim et Maria Abou Dib', 'nadim et maria abou dib', 0, NULL, 'pending'),
('isaac-and-corine', 'Philippe et Josette Aramouni', 'philippe et josette aramouni', 0, NULL, 'pending'),
('isaac-and-corine', 'Philippe et Michelle Souaid', 'philippe et michelle souaid', 0, NULL, 'pending'),
('isaac-and-corine', 'Ramzi et Therese Klink', 'ramzi et therese klink', 0, NULL, 'pending'),
('isaac-and-corine', 'Joe et Maya Hobeiche', 'joe et maya hobeiche', 0, NULL, 'pending'),
('isaac-and-corine', 'Ghassan et Denise Tambe', 'ghassan et denise tambe', 0, NULL, 'pending'),
('isaac-and-corine', 'Johnny et Tanya Keyrouz', 'johnny et tanya keyrouz', 0, NULL, 'pending'),
('isaac-and-corine', 'Charles et Anita Mansour', 'charles et anita mansour', 0, NULL, 'pending'),
('isaac-and-corine', 'Tony et Josette Gharios', 'tony et josette gharios', 0, NULL, 'pending'),
('isaac-and-corine', 'Ibrahim Abou Dib', 'ibrahim abou dib', 0, NULL, 'pending'),
('isaac-and-corine', 'Pierre et Terry Nasr', 'pierre et terry nasr', 0, NULL, 'pending'),
('isaac-and-corine', 'Tony et Dina Nasr', 'tony et dina nasr', 0, NULL, 'pending'),
('isaac-and-corine', 'Tony et Kinda Merhej', 'tony et kinda merhej', 0, NULL, 'pending'),
('isaac-and-corine', 'Jacques et Bernadette Saadé', 'jacques et bernadette saadé', 0, NULL, 'pending'),
('isaac-and-corine', 'Jean-Claude et Corine Abou Chedid', 'jean-claude et corine abou chedid', 0, NULL, 'pending'),
('isaac-and-corine', 'Raymond et Claudine Daher', 'raymond et claudine daher', 0, NULL, 'pending'),
('isaac-and-corine', 'Fouad et Joelle Zmokhol', 'fouad et joelle zmokhol', 0, NULL, 'pending'),
('isaac-and-corine', 'Georges et May Hadwan', 'georges et may hadwan', 0, NULL, 'pending'),
('isaac-and-corine', 'Tony et Katia Sayssa', 'tony et katia sayssa', 0, NULL, 'pending'),
('isaac-and-corine', 'Johnny et Martine Sayssa', 'johnny et martine sayssa', 0, NULL, 'pending'),
('isaac-and-corine', 'Nadim et May Badawi', 'nadim et may badawi', 0, NULL, 'pending'),
('isaac-and-corine', 'Patricia El Am', 'patricia el am', 0, NULL, 'pending'),
('isaac-and-corine', 'Naji et Nadine Achkar', 'naji et nadine achkar', 0, NULL, 'pending'),
('isaac-and-corine', 'Micky et Monique Chebli', 'micky et monique chebli', 0, NULL, 'pending'),
('isaac-and-corine', 'Arz et Magda El Murr', 'arz et magda el murr', 0, NULL, 'pending'),
('isaac-and-corine', 'Ronald et Lina Moussa', 'ronald et lina moussa', 0, NULL, 'pending'),
('isaac-and-corine', 'Marwan et Nayla Saadé', 'marwan et nayla saadé', 0, NULL, 'pending'),
('isaac-and-corine', 'Samir et Christiane Tamari', 'samir et christiane tamari', 0, NULL, 'pending'),
('isaac-and-corine', 'Raghid et Nada Saba', 'raghid et nada saba', 0, NULL, 'pending'),
('isaac-and-corine', 'Rami et Nazek Mortada', 'rami et nazek mortada', 0, NULL, 'pending'),
('isaac-and-corine', 'Joseph et Ghada Semaan', 'joseph et ghada semaan', 0, NULL, 'pending'),
('isaac-and-corine', 'Tony et Eliane Tamer', 'tony et eliane tamer', 0, NULL, 'pending'),
('isaac-and-corine', 'Georges et Micheline Okais', 'georges et micheline okais', 0, NULL, 'pending'),
('isaac-and-corine', 'Elias et Nadia Stephan', 'elias et nadia stephan', 0, NULL, 'pending'),
('isaac-and-corine', 'Michelle Saddi', 'michelle saddi', 0, NULL, 'pending'),
('isaac-and-corine', 'Jean et Micheline Chalouhi', 'jean et micheline chalouhi', 0, NULL, 'pending'),
('isaac-and-corine', 'Père Charbel Batour', 'père charbel batour', 0, NULL, 'pending'),
('isaac-and-corine', 'Père Denie Meyer', 'père denie meyer', 0, NULL, 'pending'),
('isaac-and-corine', 'Ghassan et Amal Salem', 'ghassan et amal salem', 0, NULL, 'pending'),
('isaac-and-corine', 'Joseph et Fifi Ayoub', 'joseph et fifi ayoub', 0, NULL, 'pending'),
('isaac-and-corine', 'Walid Ghosn', 'walid ghosn', 0, NULL, 'pending'),
('isaac-and-corine', 'Gizele Hajjar', 'gizele hajjar', 0, NULL, 'pending'),
('isaac-and-corine', 'Joseph Maalouf', 'joseph maalouf', 0, NULL, 'pending'),
('isaac-and-corine', 'Abdo et Soha Skaf', 'abdo et soha skaf', 0, NULL, 'pending'),
('isaac-and-corine', 'Bashir et Carole Farhat', 'bashir et carole farhat', 0, NULL, 'pending'),
('isaac-and-corine', 'Jihad et Marie Achkar', 'jihad et marie achkar', 0, NULL, 'pending'),
('isaac-and-corine', 'Ghassan et Kennie Chidiac', 'ghassan et kennie chidiac', 0, NULL, 'pending'),
('isaac-and-corine', 'Nabil et Dina Bazerji', 'nabil et dina bazerji', 0, NULL, 'pending'),
('isaac-and-corine', 'Nawal Ghosn', 'nawal ghosn', 0, NULL, 'pending'),
('isaac-and-corine', 'Raymond et Ghada Sadaka', 'raymond et ghada sadaka', 0, NULL, 'pending'),
('isaac-and-corine', 'Ghazi et Joumana Ghosn', 'ghazi et joumana ghosn', 0, NULL, 'pending'),
('isaac-and-corine', 'Ghosn Ghosn', 'ghosn ghosn', 0, NULL, 'pending'),
('isaac-and-corine', 'Joseph et Hanne Ghosn', 'joseph et hanne ghosn', 0, NULL, 'pending'),
('isaac-and-corine', 'Moussa Freiha', 'moussa freiha', 0, NULL, 'pending'),
('isaac-and-corine', 'Dolly Debline', 'dolly debline', 0, NULL, 'pending'),
('isaac-and-corine', 'Georges ITO test 1', 'georges ito test 1', 1, 'Test Plus One', 'pending'),
('isaac-and-corine', 'Georges ITO test 2', 'georges ito test 2', 0, NULL, 'pending'),
('isaac-and-corine', 'Georges ITO test 3', 'georges ito test 3', 0, NULL, 'pending'),
('isaac-and-corine', 'Georges ITO test 4', 'georges ito test 4', 0, NULL, 'pending'),
('isaac-and-corine', 'Georges ITO test 5', 'georges ito test 5', 0, NULL, 'pending');
